### ISSUE TITLE
Relative require should create a file

### ISSUE THREAD

**Issue by iamsergii** [HookyQR/VSCodeCreateModule#2]
I have seen that you disabled the creation of modules for the relative paths, but I would rather suggest to create a new file with `js` extension instead in that destination.

**Comment by HookyQR** [comment]
Relative require does create a new file with `.js` extension. This change avoids the suggestion popping up specifically for `require('./')` as well as `.`,`..`, and `../`. The first one is a special case require. And the other three stop the extension from suggesting what would be silly module creations.

Using `require('./newFile')` will suggest creation of (or provide a link to) `./newFile.js` as it always has done.
