### ISSUE TITLE
ES6 imports support

### ISSUE THREAD

**Issue by iamsergii** [HookyQR/VSCodeCreateModule#3]
I've managed to create a patch for  `node_modules/nodeResolve.js` file to support es6 imports syntax, but no pull request because this file is not under source control.

So to make it work I've changed 
L32 

``` js
    const _require = /require\s*\(\s*|import[\s\{\},\*\w]+(['"])(.*?[^\\])\1/g;
```

L46

``` js
    const _require = /(require\s*\(\s*|import[\s\{\},\*\w]+)(['"])(.*?[^\\])\2/g;
```

and now it works!

**Comment by HookyQR** [comment]
`node_modules/nodeResolve.js` now in repo where it should have always been. Oops.

Added optional support for ES6 modules. Workspace or user setting required: `"CreateModule.supportES6modules": true`.

**Comment by iamsergii** [comment]
thanks for the quick response,
seems to work as expected
